### PR TITLE
commands (jsreport-studio-build, jsreport-studio-start) not working on OSX

### PR DESCRIPTION
**Pull request by bjrmatos**
issue encountered while trying to publish `jsreport-jade`

command-bug

seems like a problem with the space in the hashbang, with this change i have been able to build normally

### CODE REVIEW

**Comment by bjrmatos** [comment]
same issue :(

issue

seems like the problem is windows CRLF line endings `\r`, changing CRLF to LF has solved the problem, seems like you will need to ensure that the CLI file is published with unix line endings.

solution

**Comment by pofider** [comment]
Ah, sorry, didn't know about this. It would be nice - https://github.com/npm/npm/issues/12371

I'll change to LF, publish again, test it on ubuntu VM and let you know

**Comment by bjrmatos** [comment]
thnk you!

**Comment by pofider** [comment]
Release in 1.0.2, I've tested it on ubuntu and it seems to be working.

It would take me ages to figure out this line endings issue. Thank you very much for pointing it out.

**Comment by bjrmatos** [comment]
thnks! happy to help you 😄

**Pull request merged**
